In [3]:
import pandas as pd
import numpy as np
import re
import time
import emot
from sklearn import datasets
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, roc_curve, auc
import spacy

In [36]:
a = time.time()
b = time.time()

#leo el texto eliminando duplicados
data = pd.read_csv('D:\IASaturdays\Proyecto\\limpio.csv')

#renombro columnas y elimino las Id
data = data.drop('Unnamed: 0', axis = 1)
#data = data.sample(25000)

In [37]:
#Definimos nuestra x y nuestra y

X = data['texto']
y = data['depresion']
del data

In [38]:
#definimos el pipeline

from sklearn.feature_extraction.text import TfidfVectorizer

pipeline = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('clf', MultinomialNB())
])

In [39]:
#primero creamos el vectorizador y el tfidf

tfidf_vectorizer = TfidfVectorizer()

#aplicamos count y tfidf y lo ponemos en un dataframe 
X_tfidf_df = pd.DataFrame(tfidf_vectorizer.fit_transform(X).toarray(), 
                          columns = tfidf_vectorizer.get_feature_names_out())

X_tfidf_df

,00,000,000000000000001,000000036739,000hace,005,007,00am,00h,00pm,...,ñe,ñeri,ñero,ñiee,ño,ñol_twitter,ñoquis,ños,ñoño,ñuñoinos
0,0.308588,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24996,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24997,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24998,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24999,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [40]:
#dividimos en test y train

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 27)
del X, y

Podemos ver que aquí hay muchas columnas que no tienen mucho sentido. Estas se podrían quitar con una sentencia regex. Revisa regexr.

In [41]:
# Iniciamos el modelo
model = MultinomialNB()

# Entrenamos el modelo
pipeline.fit(pd.Series(X_train), y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', MultinomialNB())])

In [42]:
y_pred = pipeline.predict(pd.Series(X_test))
y_pred

array([ True,  True,  True, ...,  True, False,  True])

In [44]:
accuracy_score(y_test, y_pred)

0.6523636363636364